# Generated by Django 3.2.19 on 2023-07-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0002_auto_20230713_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='resume_url',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='tech_skills',
        ),
        migrations.AddField(
            model_name='candidate',
            name='tech_skills',
            field=models.ManyToManyField(related_name='candidates', to='job_portal.TechSkill'),
        ),
    ]
