# Generated by Django 3.2.19 on 2023-07-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0004_candidate_resume_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='resume_url',
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
